[package]
name = "rv32jit"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "memoryapi"] }
microseh = "0.2.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.148"

[dependencies]
