[package]
name = "rv32jit"
version = "0.1.0"
edition = "2021"
default-run = "rv32jit"
rust-version = "1.78"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "memoryapi", "dwmapi", "wincon", "processenv"] }
microseh = "1.0.0"
windows = {version = "0.56.0", features = ["Win32", "Win32_System", "Win32_System_Console"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.153"

[[bin]]
name = "rv32jit"
path = "src/main.rs"

[[bin]]
name = "test_riscv_isa"
path = "src/test_riscv_isa.rs"

[profile.release] 
debug = true

[dependencies]
minifb = "0.25.0"
multiqueue = "0.3.2"
lazy_static = "1.4.0"
hashbrown = "0.14.3"
