[package]
name = "rv32jit"
version = "0.1.0"
edition = "2021"
default-run = "rv32jit"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "memoryapi", "dwmapi"] }
microseh = "1.0.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.153"

[[bin]]
name = "rv32jit"
path = "src/main.rs"

[[bin]]
name = "test_riscv_isa"
path = "src/test_riscv_isa.rs"

[features]
no_unaligned_mem_access = []
default = ["no_unaligned_mem_access"]

[profile.release] 
debug = true

[dependencies]
sdl2 = "0.36.0"
multiqueue = "0.3.2"
lazy_static = "1.4.0"
hashbrown = "0.14.3"
