[package]
name = "rv32jit"
version = "0.1.0"
edition = "2021"
default-run = "rv32jit"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "memoryapi"] }
microseh = "0.2.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.150"

[[bin]]
name = "rv32jit"
path = "src/main.rs"

[[bin]]
name = "test_riscv_isa"
path = "src/test_riscv_isa.rs"

[features]
jit = []
nojit = []

[dependencies]
chrono = "0.4.31"
sdl2 = "0.36.0"
multiqueue = "0.3.2"
lazy_static = "1.4.0"
