name: Rust CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust Nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: clippy

    - name: Build
      run: cargo build --release

    - name: Test
      run: cargo test --release RISCVBox

    - name: Zip executables (Windows)
      if: startsWith(github.ref, 'refs/tags/') && runner.os == 'windows'
      run: |
        Compress-Archive target\release\RISCVBox.exe RISCVBox.zip;

    - name: Zip executables (Linux)
      if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
      run: |
        zip -r RISCVBox.zip target/release/RISCVBox;

    - name: Upload build artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: RISCVBox-${{ matrix.os }}.zip
        path: RISCVBox.zip


  create_release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: RISCVBox-ubuntu-latest.zip
          path: build-ubuntu

      - name: Download build artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: RISCVBox-windows-latest.zip
          path: build-windows

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.DEPLOY_SECRET }}
          prerelease: false
          draft: false
          make_latest: true
          files: |
            build-ubuntu/RISCVBox-ubuntu-latest.zip
            build-windows/RISCVBox-windows-latest.zip
